apiVersion: vpc.githedgehog.com/v1beta1
kind: VPC
metadata:
  name: vpc-01
  namespace: default
spec:
  ipv4Namespace: default
  subnets:
    subnet-01:
      dhcp:
        enable: true
        range:
          end: 10.0.1.255
          start: 10.0.1.2
      gateway: 10.0.1.1
      subnet: 10.0.1.0/24
      vlan: 1001
  vlanNamespace: default
---
apiVersion: vpc.githedgehog.com/v1beta1
kind: VPCAttachment
metadata:
  name: server-01--eslag--leaf-01--leaf-02--vpc-01--subnet-01
  namespace: default
spec:
  connection: server-01--eslag--leaf-01--leaf-02
  subnet: vpc-01/subnet-01
---
apiVersion: vpc.githedgehog.com/v1beta1
kind: VPCAttachment
metadata:
  name: server-02--eslag--leaf-01--leaf-02--vpc-01--subnet-01
  namespace: default
spec:
  connection: server-02--eslag--leaf-01--leaf-02
  subnet: vpc-01/subnet-01
---
apiVersion: vpc.githedgehog.com/v1beta1
kind: VPCAttachment
metadata:
  name: server-03--eslag--leaf-01--leaf-02--vpc-01--subnet-01
  namespace: default
spec:
  connection: server-03--eslag--leaf-01--leaf-02
  subnet: vpc-01/subnet-01
---
apiVersion: vpc.githedgehog.com/v1beta1
kind: VPCAttachment
metadata:
  name: server-04--eslag--leaf-01--leaf-02--vpc-01--subnet-01
  namespace: default
spec:
  connection: server-04--eslag--leaf-01--leaf-02
  subnet: vpc-01/subnet-01
